### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by ChenZhiMing66** [nihofm/ndptmvd#2]
Hello,
I am reproducing the experimental results mentioned in your paper. I also need your help in preparing the datasets. So is it convenient for you to provide some alternative data sets for reference. Or can you tell me what your renderer is for preparing noisy and clean data?
If that is not too much trouble can you help me with providing your volume renderer?
I really need your help. Thank you very much!!!

**Comment by nihofm** [comment]
Hi,
I'm sorry, but it turned out to be impossible for us to publish any of the datasets due to data protection laws.
The cinematic renderer used in the paper is also not available to the public, so we're unfortunately unable to help you there, either.
However, I've just publicly released a volume renderer that is capable of generating volume denoising datasets. It produces datasets in hdf5 format, so with adapting the dataloader, you should be able to make something work. You can find it here: https://github.com/nihofm/volren
Best of luck with your project!
